{% set name = "unibilium" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neovim/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 370ecb07fbbc20d91d1b350c55f1c806b06bf86797e164081ccc977fc9b3af7a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('unibilium', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake >=3.10
    - make  # [unix]
    - ninja  # [win]
  host:
    - libtool  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/unibilium.h  # [unix]
    - test -f ${PREFIX}/lib/libunibilium${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\Library\bin\unibilium.dll exit /b 1  # [win]
    - if not exist %PREFIX%\Library\lib\unibilium.lib exit /b 1  # [win]
    - if not exist %PREFIX%\Library\include\unibilium.h exit /b1  # [win]

about:
  home: https://github.com/neovim/{{ name }}
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: A terminfo parsing library
  dev_url: https://github.com/neovim/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
