{% set name = "unibilium" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neovim/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6f0ee21c8605340cfbb458cbd195b4d074e6d16dd0c0e12f2627ca773f3cabf1

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libtool

test:
  commands:
    - test -f $PREFIX/lib/libunibilium${SHLIB_EXT}

about:
  home: https://www.vim.org/
  license: LGPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A terminfo parsing library
  dev_url: https://github.com/neovim/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
